### Criar Tarefa
POST http://localhost:3000/tarefas
Content-Type: application/json

{
  "titulo": "Lavar a louça do almoço",
  "descricao": "Lavar, secar e guardar tudo",
  "frequencia": "Diária",
  "status": "Pendente",
  "id_responsavel": 5, 
  "id_republica": 3
}

### Listar todas as Tarefas (Com dados de quem é o responsável)
GET http://localhost:3000/tarefas

### Atualizar Tarefa
PUT http://localhost:3000/tarefas/1
Content-Type: application/json

{
  "titulo": "Lavar a louça do JANTAR",
  "descricao": "Lavar tudo e limpar a pia",
  "frequencia": "Diária",
  "status": "Em andamento",
  "id_responsavel": 5
}

### Deletar Tarefa
DELETE http://localhost:3000/tarefas/1