### Criar república
POST http://localhost:3000/republicas
Content-Type: application/json

{
  "nome": "República Geovana",
  "codigo_acesso": "ABC123",
  "id_lider": 6
}

### Listar repúblicas
GET http://localhost:3000/republicas

### Buscar república por ID
GET http://localhost:3000/republicas/2

### Atualizar república
PUT http://localhost:3000/republicas/1
Content-Type: application/json

{
  "nome": "República Gato Místico"
}

### Deletar república
DELETE http://localhost:3000/republicas/2
